### PR TITLE
Port the Offload source code, tests and samples

### PR DESCRIPTION
**Pull request by sai-sunder-s**

### CODE REVIEW

**Review by andyrzhao — CHANGES_REQUESTED** [review]
Thanks for this PR! A high-level comment: We should not commit binaries, so please exclude everything under build/ and maybe add it to gitignore too. Precompiled binaries should be uploaded as artifacts under Github releases. We should also exclude signer_binaries/* - please let me know if those are needed for testing and we can come up with a diff strategy. For example, the enterprise-certificate-proxy repo has a platform-independent mock test signer for testing the client.

**Comment by clundin25** [comment]
@andyrzhao Let's continue this PR in https://github.com/googpleapis/enterprise-certificate-offload/pull/7. I don't have permissions to write to this branch.

I've removed the binary files from the branch.

I think we can follow up with PRs to:

1. Add a Makefile and refactor the build scripts.
2. Write a script that will pull in the signer code and build it as part of the test suite.

**Comment by shinfan** [comment]
Can you edit the .gitignore file to ignore all binaries? I am still seeing binaries in this PR.

**Comment by clundin25** [comment]
@shinfan I forked the PR to a separate one #7 because I do not have permissions to push to this repo

**Comment by shinfan** [comment]
Shall we close this one in this case?

**Pull request closed without merging**
